# Jekyll configuration for GitHub Pages
# This tells GitHub Pages to serve static files without Jekyll processing

# Disable Jekyll processing
plugins: []

# Don't process markdown files
markdown: raw

# Don't use any theme
theme: null

# Don't use any plugins
plugins: []

# Set the base URL (will be set automatically by GitHub Pages)
baseurl: ""
url: ""
